# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-03-19 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '博客表'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '分类表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签表'},
        ),
        migrations.AlterModelOptions(
            name='upanddown',
            options={'verbose_name_plural': '点赞点踩表'},
        ),
        migrations.AddField(
            model_name='article',
            name='stick',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
